### ISSUE TITLE
Win OS only?

### ISSUE THREAD

**Issue by JorySchossau** [miere43/autome#1]
What a great idea! Kudos. I got all excited for a cross-platform automation library, but it fails to run on MacOSX depending on the functions used (failed to load {kernel32, user32,...}). Looking at the source it appears there are explicit windows dependencies unless I'm reading that incorrectly. Maybe update the README.md to let people know it's for windows only?

**Comment by miere43** [comment]
Yes, unfortunately for you it's Windows-only library. Thanks for opening this issue, I'll update readme right now.
